name: 'olistproject'
version: '1.0.0'

profile: 'olistproject'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  olistproject:
    +materialized: table
    gold:
      +materialized: view
